### ISSUE TITLE
How do I install/configure TSA?

### ISSUE THREAD

**Issue by bootrider** [sandermvanvliet/sonar-typescript-plugin#2]
I have installed the plugin for SonarQube, and I am trying to perform the analysis of a Typescript project. 
whenever I try to run the analyzer, I got this:

```
INFO: Sensor TypeScriptSensor
INFO: Initializing commands
INFO: Starting tsa...
ERROR: Cannot run program "tsa" (in directory "c:\T\Unity_Plot\Rosen\Rosen.UnityPlot.Web"): createProcess error=2, The system cannot find the file specified
DEBUG: Analysis done, saving metrics
DEBUG: Metrics saved
INFO: Sensor TypeScriptSensor (done) | time=0ms
```

I copy the tsa.js file in the root of my project, as well as the lib folder one level up.

if I try to execute the script it shows an error regarding an invalid character in Line 1 character 1 Code 800A03F6.

I also installed the packages glob and FS

**Comment by sandermvanvliet** [comment]
Please add the folder where tsa is to your $PATH, then the plugin will be able to locate it.
I haven't gotten around to adding a config setting to the sonar-project.properties file yet so you can manually configure it.
